### ISSUE TITLE
fix navbar for mobile

### ISSUE THREAD

**Issue by agnaite** [agnaite/jurgita-art#10]
currently on mobile the navbar fails to autohide. fix that.

**Comment by rosswhitehouse** [comment]
Hey Agnaite,

I'd love to help out with this!

Just to check, when I load the page, the top-right nav dropdown is open, and needs to be closed by default, is that right?

Let me know :)

**Comment by MyrkaLarios** [comment]
Hi Agnaite! I'm already working on this issue :)
